# Generated by Django 4.0.4 on 2022-06-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_rented', models.BooleanField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.house')),
            ],
        ),
    ]
