# Generated by Django 4.0.4 on 2022-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cur_electricity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='cur_water',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(default='P001', max_length=4),
        ),
    ]
