# Generated by Django 4.0.4 on 2022-06-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_room'),
        ('account', '0003_rentcontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('internet_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tv_fee', models.DecimalField(decimal_places=3, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RoomConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_consump', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_consump', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.room')),
            ],
        ),
        migrations.CreateModel(
            name='BillAndReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('old_electricity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_electricity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('old_water', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_water', models.DecimalField(decimal_places=3, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tv', models.DecimalField(decimal_places=3, max_digits=10)),
                ('other', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rent_contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rentcontract')),
            ],
        ),
    ]
