# Generated by Django 4.0.4 on 2022-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billandreceipts',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billandreceipts',
            name='start_date',
            field=models.DateField(),
        ),
    ]
