# Generated by Django 4.0.4 on 2022-06-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_room'),
        ('account', '0002_account_dob_account_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tenants', models.DecimalField(decimal_places=0, max_digits=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('actual_end_date', models.DateTimeField()),
                ('internet_usage', models.BooleanField()),
                ('tv_usage', models.BooleanField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.room')),
            ],
        ),
    ]
