# Generated by Django 4.0.4 on 2022-06-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='actual_end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentcontract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
