# Generated by Django 4.0.4 on 2022-06-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='actual_end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
