# Generated by Django 4.0.4 on 2022-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_rentcontract_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
