# Generated by Django 4.0.4 on 2022-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_rentcontract_actual_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
