# Generated by Django 4.0.4 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_rentcontract_actual_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcontract',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
