# Generated by Django 3.2 on 2021-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('rooms', models.IntegerField()),
                ('is_rented', models.BooleanField(default=False)),
            ],
        ),
    ]
