# Generated by Django 3.2 on 2021-05-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='is_rented',
        ),
    ]
