# Generated by Django 3.2 on 2021-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
