# Generated by Django 3.2 on 2021-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210519_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Empty', 'Empty')], max_length=255, null=True),
        ),
    ]
