# Generated by Django 3.2 on 2021-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20210519_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
