# Generated by Django 3.2 on 2021-05-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_room_tenant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
    ]
