# Generated by Django 3.2 on 2021-05-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_conversationmessage_options'),
        ('house', '0011_alter_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
