# Generated by Django 4.0.4 on 2022-06-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_room', '0001_initial'),
        ('t_account', '0002_alter_account_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_Active', models.BooleanField(default=True)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('end_Date_Actual', models.DateField()),
                ('num_Tenants', models.IntegerField()),
                ('internet_Yes', models.BooleanField()),
                ('tv_Yes', models.BooleanField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_account.account')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_room.room')),
            ],
        ),
    ]
