# Generated by Django 4.0.4 on 2022-06-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Price', models.FloatField()),
                ('electric_Old', models.FloatField()),
                ('electric_New', models.FloatField()),
                ('water_Old', models.FloatField()),
                ('water_New', models.FloatField()),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('internet', models.FloatField()),
                ('tv', models.FloatField()),
                ('other', models.FloatField()),
                ('total', models.FloatField()),
                ('rent_Contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_bill.rentcontract')),
            ],
        ),
    ]
