# Generated by Django 3.2 on 2021-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210403_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
