# Generated by Django 3.2 on 2021-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
