# Generated by Django 3.2 on 2021-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomservices', '0003_roomservice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Processing', 'Processing')], max_length=50, null=True),
        ),
    ]
