# Generated by Django 3.2 on 2021-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EW', '0002_delete_monthlyew'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('tenant', models.TextField()),
                ('electricity_consumption', models.IntegerField()),
                ('electricity_cost', models.IntegerField()),
                ('water_consumption', models.IntegerField()),
                ('water_cost', models.IntegerField()),
                ('month', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
    ]
