# Generated by Django 3.2 on 2021-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EW', '0003_monthlyew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyew',
            name='month',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlyew',
            name='year',
            field=models.TextField(blank=True),
        ),
    ]
