# Generated by Django 4.0.4 on 2022-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Owner', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('national_ID', models.TextField()),
                ('DoB', models.DateField()),
            ],
        ),
    ]
