# Generated by Django 3.1.7 on 2021-04-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_employer',
            new_name='is_owner',
        ),
    ]
