# Generated by Django 3.1.7 on 2021-04-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210425_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='application',
        ),
    ]
