# Generated by Django 3.2 on 2021-05-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
