# Generated by Django 4.0.4 on 2022-06-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('t_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Rented', models.BooleanField(default=False)),
                ('price', models.FloatField(default=1750000)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_house.house')),
            ],
        ),
    ]
