# Generated by Django 4.0.4 on 2022-06-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Update', models.DateField()),
                ('electric_Fee', models.FloatField(default=2200)),
                ('electric_Fee_Over', models.FloatField(default=3000)),
                ('water_Fee', models.FloatField(default=10000)),
                ('water_Fee_Over', models.FloatField(default=15000)),
                ('internet_Fee', models.FloatField(default=50000)),
                ('tv_Fee', models.FloatField(default=20000)),
                ('other_Fee', models.FloatField(default=12000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_Year', models.DateField()),
                ('electric_Num', models.IntegerField()),
                ('water_Num', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_room.room')),
            ],
        ),
    ]
