# Generated by Django 4.0.4 on 2022-04-24 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_tenant_is_rented'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.TextField()),
                ('electricity_consumption', models.IntegerField()),
                ('electricity_cost', models.IntegerField()),
                ('water_consumption', models.IntegerField()),
                ('water_cost', models.IntegerField()),
                ('month', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
