# Generated by Django 3.2 on 2021-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillAndReceipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbill',
            name='month',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personalbill',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
