# Generated by Django 3.2 on 2021-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillAndReceipts', '0003_personalbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personalbill',
            name='electricity_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personalbill',
            name='electricity_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personalbill',
            name='water_consumption',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personalbill',
            name='water_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personalbill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50, null=True),
        ),
    ]
