# Generated by Django 3.2 on 2021-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
