# Generated by Django 3.2 on 2021-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='note',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
