# Generated by Django 4.0.4 on 2022-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='is_rented',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
