# Generated by Django 3.2 on 2021-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_conversationmessage_options'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='title',
        ),
        migrations.AddField(
            model_name='tenant',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_rented',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
