# Generated by Django 3.2 on 2021-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210529_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
