# Generated by Django 3.2 on 2021-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
